apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-170849160
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-170849160
    app.kubernetes.io/part-of: test-app-170849160
  name: go-170849160
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-170849160
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-170849160
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/hacdev/yco4a5rq-tenant/test-app-170849160/go-170849160@sha256:f3571d8cd952795c2639f4161dacc2adee07e285968fdf1a6b48ede2d42f8af2
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
