apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-170849160
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/yco4a5rq-tenant/test-app-170849160/go-170849160@sha256:106e513f6b943f414040ec24f25f2b6441c1c081a126cda2a3d8929d9534d0e4
        name: my-go
        resources: {}
status: {}
